title: "微软实习记录"
description: "记录我在微软实习期间的技术成长与行业认知"
theme: jekyll-theme-cayman
markdown: kramdown
navigation:
  - title: "首页"
    url: /
  - title: "技术学习"
    url: /tech
  - title: "项目展示"
    url: /projects
  - title: "行业认知"
    url: /industry
  - title: "Q&A记录"
    url: /qa
