title: "微软实习记录"
description: "记录我在微软实习期间的技术成长与行业认知"
theme: jekyll-theme-minimal

markdown: kramdown



# 导航栏配置
navigation:
  - name: 首页
    link: /
  - name: 技术学习
    link: /tech/
  - name: 项目展示
    link: /projects/
  - name: 行业认知
    link: /industry/
  - name: Q&A记录
    link: /qa/